from tkinter import *
def Delete():
    enter.delete(len(enter.get())-1,'end')
def clear():
    enter.delete(0,'end')
def take(char):
    num = char
    enter.insert('end',num) 
def result():
    E=str(enter.get())
    res = eval(E)
    enter.delete(0,"end")
    enter.insert(0,res)
root=Tk()
root.title('Calculator')
root.geometry('320x294')
a=Frame(root)
enter=Entry(a,width=52)
enter.grid(columnspan = 5)
one=Button(a,text='1',command = lambda:take(1))
one.config(bg='white',fg='black',height=3,width=10)
one.grid(column=0,row=1)
two=Button(a,text='2',command = lambda:take(2))
two.config(bg='white',fg='black',height=3,width=10)
two.grid(column=1,row=1)
three=Button(a,text='3',command = lambda:take(3))
three.config(bg='white',fg='black',height=3,width=10)
three.grid(column=2,row=1)
four=Button(a,text='4',command = lambda:take(4))
four.config(bg='white',fg='black',height=3,width=10)
four.grid(column=0,row=2)
five=Button(a,text='5',command = lambda:take(5))
five.config(bg='white',fg='black',height=3,width=10)
five.grid(column=1,row=2)
six=Button(a,text='6',command = lambda:take(6))
six.config(bg='white',fg='black',height=3,width=10)
six.grid(column=2,row=2)
seven=Button(a,text='7',command = lambda:take(7))
seven.config(bg='white',fg='black',height=3,width=10)
seven.grid(column=0,row=3)
eight=Button(a,text='8',command = lambda:take(8))
eight.config(bg='white',fg='black',height=3,width=10)
eight.grid(column=1,row=3)
nine=Button(a,text='9',command = lambda:take(9))
nine.config(bg='white',fg='black',height=3,width=10)
nine.grid(column=2,row=3)
zero=Button(a,text='0',command = lambda:take(0))
zero.config(bg='white',fg='black',height=3,width=10)
zero.grid(column=0,row=4)
clr=Button(a,text='CLEAR',command = clear)
clr.config(bg='white',fg='black',height=3,width=10)
clr.grid(column=1,row=4)
eql=Button(a,text='=',command=result)
eql.config(bg='white',fg='black',height=3,width=10)
eql.grid(column=2,row=4)
add=Button(a,text='+',command = lambda:take('+'))
add.config(bg='white',fg='black',height=3,width=10)
add.grid(column=3,row=1)
sub=Button(a,text='-',command = lambda:take('-'))
sub.config(bg='white',fg='black',height=3,width=10)
sub.grid(column=3,row=2)
mul=Button(a,text='*',command = lambda:take('*'))
mul.config(bg='white',fg='black',height=3,width=10)
mul.grid(column=3,row=3)
div=Button(a,text='/',command = lambda:take('/'))
div.config(bg='white',fg='black',height=3,width=10)
div.grid(column=3,row=4)
delete=Button(a,text='DEL',command = Delete)
delete.config(bg='white',fg='black',height=3,width=10)
delete.grid(row=5,column=0)
Quit=Button(a,text='QUIT',command=root.destroy)
Quit.config(bg='white',fg='black',height=3,width=10)
Quit.grid(row=5,column=1)
open_parenthesis=Button(a,text='(',command=lambda:take('('))
open_parenthesis.config(bg='white',fg='black',height=3,width=10)
open_parenthesis.grid(row=5,column=2)
close_parenthesis=Button(a,text=')',command=lambda:take(')'))
close_parenthesis.config(bg='white',fg='black',height=3,width=10)
close_parenthesis.grid(row=5,column=3)
a.pack()
root.mainloop()
